portfolios = [
    { "portfolioName": "Cash", "expectedGrowth": 1.63, "investmentTerm": 0 },
    { "portfolioName": "Conservative", "expectedGrowth": 4.63, "investmentTerm": 1.5 },
    { "portfolioName": "Mod Conservative", "expectedGrowth": 5.52, "investmentTerm": 3 },
    { "portfolioName": "Mod Growth", "expectedGrowth": 5.97, "investmentTerm": 4.5 },
    { "portfolioName": "Growth", "expectedGrowth": 6.72, "investmentTerm": 6 },
    { "portfolioName": "High Growth", "expectedGrowth": 6.99, "investmentTerm": 8 },
    ]
    

goals = [
     {
        "goalFrequency":'yearly',
        #"goalFrequency": "onceOff",
        "when":'date',                # age OR date OR dateRange
        "date":'2022-05-1T05:24:55.824Z',
        "dateRange": ['2021-09-19T05:28:05.535Z','2021-10-06T04:28:05.535Z'],
        "age": 65,
        "estimateType":'PV',
        "estimatedCost":120000,
        "goalType":'monetary',
        "priority": 2,
        "numTimes": 29,
        },
        {
         "goalFrequency":'onceOff',
         #"goalFrequency": "onceOff",
         "when":'date',                # age OR date OR dateRange
         "date":'2030-05-1T05:24:55.824Z',
         "dateRange": ['2021-09-19T05:28:05.535Z','2021-10-06T04:28:05.535Z'],
         "age": 65,
         "estimateType":'PV',
         "estimatedCost":120000,
         "goalType":'monetary',
         "priority": 1,
        },
                {
         "goalFrequency":'onceOff',
         #"goalFrequency": "onceOff",
         "when":'date',                # age OR date OR dateRange
         "date":'2030-05-1T05:24:55.824Z',
         "dateRange": ['2021-09-19T05:28:05.535Z','2021-10-06T04:28:05.535Z'],
         "age": 65,
         "estimateType":'PV',
         "estimatedCost":120000,
         "goalType":'monetary',
         "priority": 3,
        },

    ] 


goalsTwo = [
        {
          "arrIdx": 0,
          "assignedPortfolio": "OtherComp",
          "date": "2021-10-19T04:47:18.081Z",
          "estimateType": "PV",
          "estimatedCost": 60000,
          "goal": "Education",
          "goalFor": "joint",
          "goalFrequency": "yearly",
          "goalType": "monetary",
          "id": "Btb4G",
          "idx": 8,
          "left": 1194,
          "numTimes": 8,
          "priority": 4,
          "top": 174,
          "when": "date",
        },
        {
        "arrIdx": 9,
        "assignedPortfolio": "OtherComp",
        "date": "2022-02-08T23:18:19.576Z",
        "estimateType": "PV",
        "estimatedCost": 5000,
        "goal": "Wedding",
        "goalFor": "joint",
        "goalFrequency": "onceOff",
        "goalType": "monetary",
        "id": "bIESS",
        "idx": 19,
        "left": 85,
        "priority": 3,
        "top": -194,
        "when": "date"
        },
        {
        "arrIdx": 10,
        "assignedPortfolio": "OtherComp",
        "date": "2023-10-26T23:19:13.747Z",
        "estimateType": "PV",
        "estimatedCost": 20000,
        "goal": "Second Wedding",
        "goalFor": "joint",
        "goalFrequency": "onceOff",
        "goalType": "monetary",
        "id": "4bhGk",
        "idx": 20,
        "left": 305,
        "priority": 2,
        "top": -305,
        "when": "date",
        },
        {
        "age": 65,
        "arrIdx": 3,
        "assignedPortfolio": "CompyComp",
        "estimateType": "PV",
        "estimatedCost": 2300000,
        "goal": "Buy/Build a Residential Property",
        "goalFor": "joint",
        "goalFrequency": "onceOff",
        "goalType": "monetary",
        "id": "EXSVp",
        "idx": 14,
        "left": 922,
        "priority": 1,
        "top": 279,
        "when": "age",
        },
        {
        "arrIdx": 5,
        "assignedPortfolio": "CompyComp",
        "date": "2021-10-05T22:23:07.053Z",
        "dateRange": ['2021-10-12T06:31:13.405Z', '2021-11-17T06:31:13.405Z'],
        "estimateType": "PV",
        "estimatedCost": 1000,
        "goal": "Regular Vacations",
        "goalFor": "joint",
        "goalFrequency": "fortnightly",
        "goalType": "monetary",
        "id": "ohUiz",
        "idx": 44,
        "left": -35,
        "numTimes": 36,
        "priority": 5,
        "top": -231,
        "when": "date",
        }
]


shapedGoals = [[1000000, "one", goalsTwo], [1000000, "two", goals]]    


philosophies = {
  "requirements": [
    {
      "category": "requirements",
      "type": "residentialMortgage",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "investmentMortgage",
      "life": 1,
      "tpd": 1,
      "trauma": 0.15,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "otherDebt",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "motorVehicleLoan",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "creditCardBalance",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "personalLoan",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "marginLoanOnShares",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "childEducationExpense",
      "life": 1,
      "tpd": 1,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "rentExpense",
      "life": 1,
      "tpd": 1,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "livingExpense",
      "life": 0.75,
      "tpd": 0.75,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "generalLivingExpenses",
      "life": 0.75,
      "tpd": 0.75,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "replacementIncome",
      "life": False,
      "tpd": False,
      "trauma": 1,
      "ip": 0.75,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "replacementIncomeNumMonths",
      "life": False,
      "tpd": False,
      "trauma": 6,
      "ip": False,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "medicalRequirements",
      "life": False,
      "tpd": 200000,
      "trauma": 200000,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "extraHelpRequired",
      "life": False,
      "tpd": 30000,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "changeOfHousingCar",
      "life": False,
      "tpd": 180000,
      "trauma": False,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "lumpSumLegacy",
      "life": True,
      "tpd": False,
      "trauma": False,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "partnerTimeOffWorkInMonths",
      "life": 3,
      "tpd": 3,
      "trauma": 3,
      "ip": False,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "minimumCoveragePercentOfRequirementsPreOffsets",
      "life": 0.25,
      "tpd": 0.25,
      "trauma": 0.25,
      "ip": False,
      "for": "additionalRequirements",
    },
  ],
  "offsets": [

    {
      "category": "offsets",
      "type": "investmentProperty",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "nonCashInvestments",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0.5,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "superAndPension",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "cash",
      "life": 1,
      "tpd": 1,
      "trauma": 0.85,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "offsetAccounts",
      "life": 100,
      "tpd": 100,
      "trauma": 30,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "artOrAntique",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "incomeProtector", 
      "life": False,
      "tpd": 1,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    
    {
      "category": "offsets",
      "type": "livingPartnerIncome",
      "life": 0.5,
      "tpd": 1,
      "trauma": 0,
      "ip": 0,
      "for": "incomes",
    },
    {
      "category": "offsets",
      "type": "otherIncome",
      "life": 1,
      "tpd": 1,
      "trauma": 1,
      "ip": 0,
      "for": "incomes",
    },
    {
      "category": "offsets",
      "type": "otherLumpSums",
      "life": 1,
      "tpd": 1,
      "trauma": 0,
      "ip": 0,
      "for": "additionalRequirements",
    },
  ],
  "steppedVsLevel": [
    {
      "category": "steppedVsLevel",
      "type": "transitionFromLevelToStepped",
      "life": True,
      "tpd": True,
      "trauma": True,
      "ip": False,
      "for": "insurance",
    },
    {
      "category": "steppedVsLevel",
      "type": "numYearsOnLevel",
      "life": 15,
      "tpd": 15,
      "trauma": 15,
      "ip": 15,
      "for": "insurance",
    },
    {
      "category": "steppedVsLevel",
      "type": "percentOnStepped",
      "life": 0.25,
      "tpd": 0.25,
      "trauma": 0.25,
      "ip": 0.25,
      "for": "insurance",
    },
  ],
};

"""
assumptions = {
  "growthRate": {
    "CPI": 2,
    "livingExpense": 1,
    "education": 4,
    "GACPI": 2.5,
    "depreciatingAsset": -15,
  },
  "investmentReturns": {
    "income": 50,
    "expenses": 50,
  },
  "reductions": {
    "marketValue": 15,
    "livingExpenseInDeathOfPartner": 25,
    "livingExpenseInRetirement": 20,
    "other": 0,
  },
  "taxation": {
    "taxOnIncomeGrowth": 30,
    "taxOnCapitalGrowth": 10,
    "taxOnFutureCapitalGrowth": 15,
    "taxOnLumpSumInsurance": 10,
  },
  "other": {
    "mortalityAge": 95,
    "yearsOnLevelPremium": 15,
    "maximumAgeForIncomeProtection": 70,
    "maximumAgeToFundChildren": 25,
    "retirementAge": 70,
    "behaviourModificationLoading": 25, 
  },
};
"""

assumptions = [
  {
    "id": 1,
    "fieldname": "Growth Rate",
    "field": "CPI",
    "type": "CPI",
    "value": 2.8, # 2
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 2,
    "fieldname": "Growth Rate",
    "field": "Living Expenses",
    "type": "livingExpense",
    "value": 1,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 23,
    "fieldname": "Growth Rate",
    "field": "Medical Inflation",
    "type": "medicalInflation",
    "value": 5,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 24,
    "fieldname": "Growth Rate",
    "field": "Real Estate",
    "type": "realEstate",
    "value": 6,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 3,
    "fieldname": "Growth Rate",
    "field": "Education",
    "type": "education",
    "value": 4,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 4,
    "fieldname": "Growth Rate",
    "field": "Default Portfolio Growth Rate for Calculations",
    "type": "defaultGrowthRate",
    "value": "Mod Conservative",
    "valueType": "select",
    "for": "growthRate",
  },
  {
    "id": 5,
    "fieldname": "Growth Rate",
    "field": "Depreciating Asset",
    "type": "depreciatingAsset",
    "value": -15,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 6,
    "fieldname": "Investment Returns",
    "field": "Incomes",
    "type": "income",
    "value": 50,
    "valueType": "percent",
    "for": "investmentReturns",
  },
  {
    "id": 7,
    "fieldname": "Investment Returns",
    "field": "Expenses",
    "type": "expenses",
    "value": 50,
    "valueType": "percent",
    "for": "investmentReturns",
  },
  {
    "id": 8,
    "fieldname": "Reductions",
    "field": "Market Value",
    "type": "marketValue",
    "value": 15,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 9,
    "fieldname": "Reductions",
    "field": "Living Expenses (in death or disability of insured)",
    "type": "livingExpenseInDeathOfPartner",
    "value": 25,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 10,
    "fieldname": "Reductions",
    "field": "Living Expenses (in retirement)",
    "type": "livingExpenseInRetirement",
    "value": 20,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 11,
    "fieldname": "Reductions",
    "field": "Other",
    "type": "other",
    "value": 0,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 12,
    "fieldname": "Taxation",
    "field": "Tax on Income Growth",
    "type": "taxOnIncomeGrowth",
    "value": 30,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 13,
    "fieldname": "Taxation",
    "field": "Tax on Capital Growth",
    "type": "taxOnFutureCapitalGrowth",
    "value": 15,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 14,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payments (e.g. Super/Life Insurance)",
    "type": "taxOnLumpSumPaymentsLife",
    "value": 0,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 15,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payment (TPD)",
    "type": "taxOnLumpSumPaymentsTPD",
    "value": 10,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 16,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payment (Trauma)",
    "type": "taxOnLumpSumPaymentsTrauma",
    "value": 0,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 17,
    "fieldname": "Other",
    "field": "Mortality Age",
    "type": "mortalityAge",
    "value": 95,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 18,
    "fieldname": "Other",
    "field": "Retirement Age",
    "type": "retirementAge",
    "value": 90,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 19,
    "fieldname": "Other",
    "field": "Years on Level Premium",
    "type": "yearsOnLevelPremium",
    "value": 15,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 20,
    "fieldname": "Other",
    "field": "Maximum Age for Income Protection",
    "type": "maximumAgeForIncomeProtection",
    "value": 0,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 21,
    "fieldname": "Other",
    "field": "Maximum Age to Fund Children",
    "type": "maximumAgeToFundChildren",
    "value": 25,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 22,
    "fieldname": "Other",
    "field": "Behaviour Modification Loading",
    "type": "behaviourModificationLoading",
    "value": 25,
    "valueType": "percent",
    "for": "other",
  },
];

clientData = { 
  "hasPartner": True,
  "hasDependents": False,
  "hasChildren": True,
  "hasJointDependents": False,
  "hasPartnerDependents": False,
  "insuranceInfo": {
    "estatePlanning": {},
    "existingCover": [],
  },
  "riskProfile": {
      "portfolioRate": 4.5
  },
  "primary": {
    "firstName": "Male",
    "lastName": "Test",
    "dateOfBirth": "Fri Dec 25 1935",
    "relationshipStatus": "married",
    "gender": "male",
    "expenses": [
#      {
#        "class": "livingExpense",
#        "type": "generalLivingExpenses",
#        "value": 100000,
#      },
  
    ],
    "liabilities": [
        {
        "class": "mortgage",
        "type": "residentialMortgage",
        "value": 500000,
        },
        {
        "class": "lumpSumLegacy",
        "type":"lumpSumLegacy",
        "value": 100000
        },
    ],
    "assets": [
      {
        "class": "superAndPension",
        "type": "accountBasedPension",
        "value": 200000,
        "notes": "SA Department of Health Pension Fund",
      },
      {
        "class": "realEstate",
        "type": "familyHome",
        "value": 1000000,
      },
    ],
    "incomes": [
      #   {
      #   "class": "personalIncome",
      #   "type": "salaryIncome",
      #   "value": 91636/2,
      # },
        
        ],
    "healthStatus": "",
    "retirementAge": 95,
  },
  "joint": {
    "expenses": [      {
        "class": "livingExpense",
        "type": "generalLivingExpenses",
        "value": 100000,
      },],
    "liabilities": [],
    "assets": [],
    "incomes": [],
  },
  "partner": {
    "firstName": "Female",
    "lastName": "Test",
    "dateOfBirth": "Fri Dec 25 1936",
    "gender": "female",
    "expenses": [
    ],
    "assets": [
      {
        "class": "cash",
        "type": "bankAccount",
        "value": 100000,
      },
    ],
    "incomes": [
      # {
      #   "class": "personalIncome",
      #   "type": "salaryIncome",
      #   "value": 91636,
      # },
      #      {
      #   "class": "personalIncome",
      #   "type": "bonusIncome",
      #   "value": 91636/3,
      # },
        ],
    "healthStatus": "",
    "retirementAge": 70,
  },
  "advisors": [],
  "dependents": [],
  "children": [
    {
      "firstName": "Child",
      "lastName": "Test",
      "legacyNominee": True,
      "dateOfBirth": "Wed Jan 1 2000",
      "expenses": [
        {
          "class": "childExpense",
          "type": "childEducationExpense",
          "value": 25000,
        },               
      ],
    },
  ],
  "partnerDependents": [],
  "jointDependents": [],

  "values": {
    "selectedVals": [],
    "topVals": [],
  },
 "goals": {},
}