philosophies = {
  "requirements": [
    {
      "category": "requirements",
      "type": "residentialMortgage",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "investmentMortgage",
      "life": 1,
      "tpd": 1,
      "trauma": 0.15,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "otherDebt",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "motorVehicleLoan",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "creditCardBalance",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "personalLoan",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "marginLoanOnShares",
      "life": 1,
      "tpd": 1,
      "trauma": 0.3,
      "ip": False,
      "for": "liabilities",
    },
    {
      "category": "requirements",
      "type": "childEducationExpense",
      "life": 1,
      "tpd": 1,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "rentExpense",
      "life": 1,
      "tpd": 1,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "livingExpense",
      "life": 0.75,
      "tpd": 0.75,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "generalLivingExpenses",
      "life": 0.75,
      "tpd": 0.75,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "replacementIncome",
      "life": False,
      "tpd": False,
      "trauma": 1,
      "ip": 0.75,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "replacementIncomeNumMonths",
      "life": False,
      "tpd": False,
      "trauma": 6,
      "ip": False,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "medicalRequirements",
      "life": False,
      "tpd": 200000,
      "trauma": 200000,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "extraHelpRequired",
      "life": False,
      "tpd": 30000,
      "trauma": False,
      "ip": False,
      "for": "expenses",
    },
    {
      "category": "requirements",
      "type": "changeOfHousingCar",
      "life": False,
      "tpd": 180000,
      "trauma": False,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "lumpSumLegacy",
      "life": True,
      "tpd": False,
      "trauma": False,
      "ip": False,
      "for": "additionalRequirements",
    },
    {
      "category": "requirements",
      "type": "partnerTimeOffWorkInMonths",
      "life": 3,
      "tpd": 3,
      "trauma": 3,
      "ip": False,
      "for": "incomes",
    },
    {
      "category": "requirements",
      "type": "minimumCoveragePercentOfRequirementsPreOffsets",
      "life": 0.25,
      "tpd": 0.25,
      "trauma": 0.25,
      "ip": False,
      "for": "additionalRequirements",
    },
  ],
  "offsets": [

    {
      "category": "offsets",
      "type": "investmentProperty",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "nonCashInvestments",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0.5,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "superAndPension",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "cash",
      "life": 1,
      "tpd": 1,
      "trauma": 0.85,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "offsetAccounts",
      "life": 100,
      "tpd": 100,
      "trauma": 30,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "artOrAntique",
      "life": 0.85,
      "tpd": 0.85,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    {
      "category": "offsets",
      "type": "incomeProtector", 
      "life": False,
      "tpd": 1,
      "trauma": 0,
      "ip": False,
      "for": "assets",
    },
    
    {
      "category": "offsets",
      "type": "livingPartnerIncome",
      "life": 0.5,
      "tpd": 1,
      "trauma": 0,
      "ip": 0,
      "for": "incomes",
    },
    {
      "category": "offsets",
      "type": "otherIncome",
      "life": 1,
      "tpd": 1,
      "trauma": 1,
      "ip": 0,
      "for": "incomes",
    },
    {
      "category": "offsets",
      "type": "otherLumpSums",
      "life": 1,
      "tpd": 1,
      "trauma": 0,
      "ip": 0,
      "for": "additionalRequirements",
    },
  ],
  "steppedVsLevel": [
    {
      "category": "steppedVsLevel",
      "type": "transitionFromLevelToStepped",
      "life": True,
      "tpd": True,
      "trauma": True,
      "ip": False,
      "for": "insurance",
    },
    {
      "category": "steppedVsLevel",
      "type": "numYearsOnLevel",
      "life": 15,
      "tpd": 15,
      "trauma": 15,
      "ip": 15,
      "for": "insurance",
    },
    {
      "category": "steppedVsLevel",
      "type": "percentOnStepped",
      "life": 0.25,
      "tpd": 0.25,
      "trauma": 0.25,
      "ip": 0.25,
      "for": "insurance",
    },
  ],
};

"""
assumptions = {
  "growthRate": {
    "CPI": 2,
    "livingExpense": 1,
    "education": 4,
    "GACPI": 2.5,
    "depreciatingAsset": -15,
  },
  "investmentReturns": {
    "income": 50,
    "expenses": 50,
  },
  "reductions": {
    "marketValue": 15,
    "livingExpenseInDeathOfPartner": 25,
    "livingExpenseInRetirement": 20,
    "other": 0,
  },
  "taxation": {
    "taxOnIncomeGrowth": 30,
    "taxOnCapitalGrowth": 10,
    "taxOnFutureCapitalGrowth": 15,
    "taxOnLumpSumInsurance": 10,
  },
  "other": {
    "mortalityAge": 95,
    "yearsOnLevelPremium": 15,
    "maximumAgeForIncomeProtection": 70,
    "maximumAgeToFundChildren": 25,
    "retirementAge": 70,
    "behaviourModificationLoading": 25, 
  },
};
"""

assumptions = [
  {
    "id": 1,
    "fieldname": "Growth Rate",
    "field": "CPI",
    "type": "CPI",
    "value": 2,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 2,
    "fieldname": "Growth Rate",
    "field": "Living Expenses",
    "type": "livingExpense",
    "value": 1,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 23,
    "fieldname": "Growth Rate",
    "field": "Medical Inflation",
    "type": "medicalInflation",
    "value": 5,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 24,
    "fieldname": "Growth Rate",
    "field": "Real Estate",
    "type": "realEstate",
    "value": 6,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 3,
    "fieldname": "Growth Rate",
    "field": "Education",
    "type": "education",
    "value": 4,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 4,
    "fieldname": "Growth Rate",
    "field": "Default Portfolio Growth Rate for Calculations",
    "type": "defaultGrowthRate",
    "value": "Mod Conservative",
    "valueType": "select",
    "for": "growthRate",
  },
  {
    "id": 5,
    "fieldname": "Growth Rate",
    "field": "Depreciating Asset",
    "type": "depreciatingAsset",
    "value": -15,
    "valueType": "percent",
    "for": "growthRate",
  },
  {
    "id": 6,
    "fieldname": "Investment Returns",
    "field": "Incomes",
    "type": "income",
    "value": 50,
    "valueType": "percent",
    "for": "investmentReturns",
  },
  {
    "id": 7,
    "fieldname": "Investment Returns",
    "field": "Expenses",
    "type": "expenses",
    "value": 50,
    "valueType": "percent",
    "for": "investmentReturns",
  },
  {
    "id": 8,
    "fieldname": "Reductions",
    "field": "Market Value",
    "type": "marketValue",
    "value": 15,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 9,
    "fieldname": "Reductions",
    "field": "Living Expenses (in death or disability of insured)",
    "type": "livingExpenseInDeathOfPartner",
    "value": 25,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 10,
    "fieldname": "Reductions",
    "field": "Living Expenses (in retirement)",
    "type": "livingExpenseInRetirement",
    "value": 20,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 11,
    "fieldname": "Reductions",
    "field": "Other",
    "type": "other",
    "value": 0,
    "valueType": "percent",
    "for": "reductions",
  },
  {
    "id": 12,
    "fieldname": "Taxation",
    "field": "Tax on Income Growth",
    "type": "taxOnIncomeGrowth",
    "value": 30,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 13,
    "fieldname": "Taxation",
    "field": "Tax on Capital Growth",
    "type": "taxOnFutureCapitalGrowth",
    "value": 15,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 14,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payments (e.g. Super/Life Insurance)",
    "type": "taxOnLumpSumPaymentsLife",
    "value": 0,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 15,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payment (TPD)",
    "type": "taxOnLumpSumPaymentsTPD",
    "value": 10,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 16,
    "fieldname": "Taxation",
    "field": "Tax on Lump Sum Payment (Trauma)",
    "type": "taxOnLumpSumPaymentsTrauma",
    "value": 0,
    "valueType": "percent",
    "for": "taxation",
  },
  {
    "id": 17,
    "fieldname": "Other",
    "field": "Mortality Age",
    "type": "mortalityAge",
    "value": 95,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 18,
    "fieldname": "Other",
    "field": "Retirement Age",
    "type": "retirementAge",
    "value": 65,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 19,
    "fieldname": "Other",
    "field": "Years on Level Premium",
    "type": "yearsOnLevelPremium",
    "value": 15,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 20,
    "fieldname": "Other",
    "field": "Maximum Age for Income Protection",
    "type": "maximumAgeForIncomeProtection",
    "value": 0,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 21,
    "fieldname": "Other",
    "field": "Maximum Age to Fund Children",
    "type": "maximumAgeToFundChildren",
    "value": 25,
    "valueType": "number",
    "for": "other",
  },
  {
    "id": 22,
    "fieldname": "Other",
    "field": "Behaviour Modification Loading",
    "type": "behaviourModificationLoading",
    "value": 25,
    "valueType": "percent",
    "for": "other",
  },
];

clientData = { 
  "hasPartner": True,
  "hasDependents": False,
  "hasChildren": True,
  "hasJointDependents": False,
  "hasPartnerDependents": False,
  "insuranceInfo": {
    "estatePlanning": {},
    "existingCover": [],
  },
  "riskProfile": {
      "portfolioRate": 0.035
  },
  "primary": {
    "firstName": "Tjaart",
    "lastName": "van der Westhuizen",
    "dateOfBirth": "Fri Jun 25 1979",
    "relationshipStatus": "married",
    "gender": "male",
    "expenses": [
      {
        "class": "homeExpense",
        "type": "rentExpense",
        "value": 12500,
      },
      {
        "class": "insuranceExpense",
        "type": "privateHealthInsuranceExpense",
        "value": 4269,
      },
      {
        "class": "insuranceExpense",
        "type": "vehicleInsuranceExpense",
        "value": 587,
      },
      {
        "class": "investmentExpense",
        "type": "investmentBondsExpense",
        "value": 2105,
      },
      {
        "class": "insuranceExpense",
        "type": "lifeInsuranceExpense",
        "value": 5008,
      },
      {
        "class": "insuranceExpense",
        "type": "homeInsuranceExpense",
        "value": 4965,
      },
      {
        "class": "homeExpense",
        "type": "homeUtilitiesExpense",
        "value": 1800,
      },
    ],
    "liabilities": [],
    "assets": [
      {
        "class": "otherInvestments",
        "type": "bonds",
        "value": 124510,
        "notes": "SA Alan Gray Annuity",
      },
      {
        "class": "otherInvestments",
        "type": "bonds",
        "value": 7017,
        "notes": "SA Alan Gray Annuity",
      },
    ],
    "incomes": [
      {
        "class": "personalIncome",
        "type": "salaryIncome",
        "value": 91636,
      },
      {
        "class": "investmentIncome",
        "type": "investmentPropertyIncome",
        "value": 38181,
      },
    ],
    "healthStatus": "",
    "retirementAge": 65,
  },
  "joint": {
    "expenses": [],
    "liabilities": [],
    "assets": [],
    "incomes": [],
  },
  "partner": {
    "firstName": "Cecile",
    "lastName": "van der Westhuizen",
    "dateOfBirth": "Fri Jun 25 1979",
    "gender": "female",
    "expenses": [
      {
        "class": "financialExpense",
        "type": "personalLoanExpense",
        "value": 4108,
      },
      {
        "class": "insuranceExpense",
        "type": "vehicleInsuranceExpense",
        "value": 600,
      },
      {
        "class": "investmentExpense",
        "type": "investmentBondsExpense",
        "value": 1520,
      },
      {
        "class": "homeExpense",
        "type": "ratesAndTaxesExpense",
        "value": 2052,
      },
      {
        "class": "homeExpense",
        "type": "homeEntertainmentExpense",
        "value": 840,
      },
      {
        "class": "livingExpense",
        "type": "generalLivingExpenses",
        "value": 50000,
      },
      {
        "class": "insuranceExpense",
        "type": "lifeInsuranceExpense",
        "value": 5008,
      },
    ],
    "liabilities": [
      {
        "class": "mortgage",
        "type": "residentialMortgage",
        "value": 80100,
      },
      {
        "class": "otherLoans",
        "type": "motorVehicleLoan",
        "value": 10000,
      },
    ],
    "assets": [
      {
        "class": "superAndPension",
        "type": "accountBasedPension",
        "value": 136142,
        "notes": "SA Department of Health Pension Fund",
      },
      {
        "class": "otherInvestments",
        "type": "bonds",
        "value": 90000,
        "notes": "SA Alan Gray Annuity",
      },
      {
        "class": "otherInvestments",
        "type": "bonds",
        "value": 21450,
        "notes": "SA Alan Gray Unit Trust",
      },
      {
        "class": "realEstate",
        "type": "investmentProperty",
        "value": 225000,
        "notes": "Share of SA property in Lynnwood",
      },
    ],
    "incomes": [
      {
        "class": "personalIncome",
        "type": "salaryIncome",
        "value": 247000,
      },
      {
        "class": "personalIncome",
        "type": "otherIncome",
        "value": 9010,
      },
    ],
    "healthStatus": "",
    "retirementAge": 70,
  },
  "advisors": [],
  "dependents": [],
  "children": [
    {
      "firstName": "Nikolas",
      "lastName": "van der Westhuizen",
      "legacyNominee": True,
      "dateOfBirth": "Wed Jan 1 2015",
      "expenses": [
        {
          "class": "childExpense",
          "type": "childEducationExpense",
          "value": 30000,
        },               
      ],
    },
    {
      "firstName": "Lienke",
      "lastName": "van der Westhuizen",
      "legacyNominee": True,
      "dateOfBirth": "Wed Jan 1 2015",
      "expenses": [
        {
          "class": "childExpense",
          "type": "childEducationExpense",
          "value": 30000,
        },
      ],
    },
  ],
  "partnerDependents": [],
  "jointDependents": [],

  "values": {
    "selectedVals": [],
    "topVals": [],
  },
 "goals": {},
}