export const globals = [
  {
    inflationRate: 2.8,
    behaviourModificationLoading: 25,
    riskProfileAsPerPortfolioPercentGrowth: 5,
  },
];
// import { createId } from '../../helpers/util';

export const emptyPortfolio = {
  allocations: {
    Alternative: 0,
    Cash: 0,
    "Domestic Equity": 0,
    "Domestic Fixed Interest": 0,
    "Domestic Property": 0,
    "International Equity": 0,
    "International Fixed Interest": 0,
    "International Property": 0,
  },
  bands: { high: 100, low: 100, portfolio: "", id: "" },
  portfolioName: "",
  investmentTerm: 0,
  expectedGrowth: 0,
  probabilityNegativeReturn: 0,
  id: "",
};

export const portfolios = [
  {
    id: "0",
    portfolioName: "Cash",
    investmentTerm: 0.5,
    expectedGrowth: 2,
  },
  {
    id: "2",
    portfolioName: "Conservative",
    investmentTerm: 1.5,
    expectedGrowth: 3,
  },
  {
    id: "3",
    portfolioName: "Mod Conservative",
    investmentTerm: 3,
    expectedGrowth: 4,
  },
  {
    id: "4",
    portfolioName: "Mod Growth",
    investmentTerm: 4.5,
    expectedGrowth: 5,
  },
  {
    id: "5",
    portfolioName: "Growth",
    investmentTerm: 6,
    expectedGrowth: 6,
  },
  {
    id: "6",
    portfolioName: "High Growth",
    investmentTerm: 8,
    expectedGrowth: 7,
  },
];

export const assumptionsCols = [
  { field: "fieldname", header: "x", type: "uneditable" },
  { field: "field", header: "y", type: "uneditable" },
  { field: "value", header: "z", type: "number" },
];

export const assumptions = [
  {
    id: 1,
    fieldname: "Growth Rate",
    field: "CPI",
    type: "CPI",
    value: 2,
    valueType: "percent",
    for: "growthRate",
  },
  // {
  //   id: 2,
  //   fieldname: "Growth Rate",
  //   field: "Living Expenses",
  //   type: "livingExpense",
  //   value: 1,
  //   valueType: "percent",
  //   for: "growthRate",
  // },
  {
    id: 23,
    fieldname: "Growth Rate",
    field: "Medical Inflation",
    type: "medicalInflation",
    value: 5,
    valueType: "percent",
    for: "growthRate",
  },
  {
    id: 24,
    fieldname: "Growth Rate",
    field: "Real Estate",
    type: "realEstate",
    value: 6,
    valueType: "percent",
    for: "growthRate",
  },
  {
    id: 3,
    fieldname: "Growth Rate",
    field: "Education",
    type: "education",
    value: 4,
    valueType: "percent",
    for: "growthRate",
  },
  {
    id: 4,
    fieldname: "Growth Rate",
    field: "Default Portfolio Growth Rate for Calculations",
    type: "defaultGrowthRate",
    value: "Mod Conservative",
    valueType: "select",
    for: "growthRate",
  },
  {
    id: 5,
    fieldname: "Growth Rate",
    field: "Depreciating Asset",
    type: "depreciatingAsset",
    value: -15,
    valueType: "percent",
    for: "growthRate",
  },
  {
    id: 6,
    fieldname: "Investment Returns",
    field: "Incomes",
    type: "income",
    value: 50,
    valueType: "percent",
    for: "investmentReturns",
  },
  {
    id: 7,
    fieldname: "Investment Returns",
    field: "Expenses",
    type: "expenses",
    value: 50,
    valueType: "percent",
    for: "investmentReturns",
  },
  {
    id: 8,
    fieldname: "Reductions",
    field: "Market Value",
    type: "marketValue",
    value: 15,
    valueType: "percent",
    for: "reductions",
  },
  {
    id: 9,
    fieldname: "Reductions",
    field: "Living Expenses (in death or disability of insured)",
    type: "livingExpenseInDeathOfPartner",
    value: 25,
    valueType: "percent",
    for: "reductions",
  },
  {
    id: 10,
    fieldname: "Reductions",
    field: "Living Expenses (in retirement)",
    type: "livingExpenseInRetirement",
    value: 20,
    valueType: "percent",
    for: "reductions",
  },
  {
    id: 11,
    fieldname: "Reductions",
    field: "Other",
    type: "other",
    value: 0,
    valueType: "percent",
    for: "reductions",
  },
  {
    id: 12,
    fieldname: "Taxation",
    field: "Tax on Income Growth",
    type: "taxOnIncomeGrowth",
    value: 30,
    valueType: "percent",
    for: "taxation",
  },
  {
    id: 13,
    fieldname: "Taxation",
    field: "Tax on Capital Growth",
    type: "taxOnFutureCapitalGrowth",
    value: 15,
    valueType: "percent",
    for: "taxation",
  },
  {
    id: 14,
    fieldname: "Taxation",
    field: "Tax on Lump Sum Payments (e.g. Super/Life Insurance)",
    type: "taxOnLumpSumPaymentsLife",
    value: 0,
    valueType: "percent",
    for: "taxation",
  },
  {
    id: 15,
    fieldname: "Taxation",
    field: "Tax on Lump Sum Payment (TPD)",
    type: "taxOnLumpSumPaymentsTPD",
    value: 10,
    valueType: "percent",
    for: "taxation",
  },
  {
    id: 16,
    fieldname: "Taxation",
    field: "Tax on Lump Sum Payment (Trauma)",
    type: "taxOnLumpSumPaymentsTrauma",
    value: 0,
    valueType: "percent",
    for: "taxation",
  },
  {
    id: 17,
    fieldname: "Other",
    field: "Mortality Age",
    type: "mortalityAge",
    value: 95,
    valueType: "number",
    for: "other",
  },
  {
    id: 18,
    fieldname: "Other",
    field: "Retirement Age",
    type: "retirementAge",
    value: 65,
    valueType: "number",
    for: "other",
  },
  {
    id: 19,
    fieldname: "Other",
    field: "Years on Level Premium",
    type: "yearsOnLevelPremium",
    value: 15,
    valueType: "number",
    for: "other",
  },
  {
    id: 20,
    fieldname: "Other",
    field: "Maximum Age for Income Protection",
    type: "maximumAgeForIncomeProtection",
    value: 0,
    valueType: "number",
    for: "other",
  },
  {
    id: 21,
    fieldname: "Other",
    field: "Maximum Age to Fund Children",
    type: "maximumAgeToFundChildren",
    value: 25,
    valueType: "number",
    for: "other",
  },
  {
    id: 22,
    fieldname: "Other",
    field: "Behaviour Modification Loading",
    type: "behaviourModificationLoading",
    value: 25,
    valueType: "percent",
    for: "other",
  },
];

export const philosophies = {
  requirements: [
    {
      id: 1,
      fieldname: "Mortgage - Residential",
      type: "residentialMortgage",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 2,
      fieldname: "Mortgage - Investment",
      type: "investmentMortgage",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 15,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 3,
      fieldname: "Car Finance",
      type: "motorVehicleLoan",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 4,
      fieldname: "Credit Card",
      type: "creditCardBalance",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 5,
      fieldname: "Personal Loan",
      type: "personalLoan",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 6,
      fieldname: "Margin Loan on Shares",
      type: "marginLoanOnShares",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 15,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 7,
      fieldname: "Other Debt",
      type: "otherDebt",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: 15,
      ip: undefined,
      for: "liabilities",
      valueType: "percent",
    },
    {
      id: 8,
      fieldname: "Family Living Expenses",
      type: "livingExpense",
      category: "requirements",
      life: 75,
      tpd: 75,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
      valueType: "percent",
    },
    {
      id: 9,
      fieldname: "Children's Education",
      type: "childEducationExpense",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
      valueType: "percent",
    },
    {
      id: 10,
      fieldname: "Rental",
      type: "rentExpense",
      category: "requirements",
      life: 100,
      tpd: 100,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
      valueType: "percent",
    },
    {
      id: 11,
      fieldname: "Extra Help Required",
      type: "extraHelpRequired",
      category: "requirements",
      life: undefined,
      tpd: 30000,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
      valueType: "price",
    },
    {
      id: 12,
      fieldname: "Replacement Income",
      type: "replacementIncome",
      category: "requirements",
      life: undefined,
      tpd: undefined,
      trauma: 100,
      ip: 75,
      for: "incomes",
      valueType: "percent",
    },
    {
      id: 13,
      fieldname: "Replacement Income (# months)",
      type: "replacementIncomeNumMonths",
      category: "requirements",
      life: undefined,
      tpd: undefined,
      trauma: 6,
      ip: undefined,
      for: "incomes",
      valueType: "number",
    },
    {
      id: 14,
      fieldname: "Medical Requirements",
      type: "medicalRequirements",
      category: "requirements",
      life: undefined,
      tpd: 200000,
      trauma: 200000,
      ip: undefined,
      for: "additionalRequirements",
      valueType: "price",
    },
    {
      id: 15,
      fieldname: "Change of Housing/Car",
      type: "changeOfHousingCar",
      category: "requirements",
      life: undefined,
      tpd: 180000,
      trauma: undefined,
      ip: undefined,
      for: "additionalRequirements",
      valueType: "price",
    },
    {
      id: 16,
      fieldname: "Lump Sum Legacy",
      type: "lumpSumLegacy",
      category: "requirements",
      life: true,
      tpd: false,
      trauma: false,
      ip: false,
      for: "additionalRequirements",
      valueType: "boolean",
    },
    {
      id: 17,
      fieldname: "Tax on Lump Sum Insurance Payment",
      type: "lumpSumInsurance",
      category: "requirements",
      life: 1.5,
      tpd: 1.5,
      trauma: 1,
      ip: 1,
      for: "additionalRequirements",
      valueType: "boolean",
    },
    {
      id: 18,
      fieldname: "Partner Time Off Work (months)",
      type: "partnerTimeOffWorkInMonths",
      category: "requirements",
      life: 3,
      tpd: 3,
      trauma: 3,
      ip: undefined,
      for: "incomes",
      valueType: "number",
    },
    {
      id: 19,
      fieldname: "Minimum Coverage (% of requirements pre-offsets)",
      type: "minimumCoveragePercentOfRequirementsPreOffsets",
      category: "requirements",
      life: 25,
      tpd: 25,
      trauma: 25,
      ip: undefined,
      for: "additionalRequirements",
      valueType: "percent",
    },
  ],
  offsets: [
    // ASSETS:
    {
      category: "offsets",
      fieldname: "Investment Property",
      type: "investmentProperty",
      life: 85,
      tpd: 85,
      trauma: 0,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    // Any investment/asset that is not cash or investmentProperty or art:
    {
      category: "offsets",
      fieldname: "Non-cash Investments",
      type: "nonCashInvestments",
      life: 85,
      tpd: 85,
      trauma: 50,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Pension and Superannnuation",
      type: "superAndPension",
      life: 85,
      tpd: 85,
      trauma: 0,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Cash Accounts",
      type: "cash",
      life: 100,
      tpd: 100,
      trauma: 85,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    // WHAT ARE THESE?
    {
      category: "offsets",
      fieldname: "Offset Accounts",
      type: "offsetAccounts",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Art & Antiques",
      type: "artOrAntique",
      life: 85,
      tpd: 85,
      trauma: 0,
      ip: undefined,
      for: "assets",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Income Protector",
      type: "incomeProtector", // ??
      life: 0,
      tpd: 100,
      trauma: 0,
      ip: 0,
      for: "assets",
      valueType: "percent",
    },
    // INCOME
    {
      category: "offsets",
      fieldname: "Partner Income",
      type: "livingPartnerIncome",
      life: 50,
      tpd: 100,
      trauma: 0,
      ip: 0,
      for: "incomes",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Any other sources of Income",
      type: "otherIncome",
      life: 100,
      tpd: 100,
      trauma: 100,
      ip: 100,
      for: "incomes",
      valueType: "percent",
    },
    {
      category: "offsets",
      fieldname: "Any other sources of Lump Sums",
      type: "otherLumpSums",
      life: 100,
      tpd: 100,
      trauma: 0,
      ip: 0,
      for: "additionalRequirements",
      valueType: "percent",
    },
  ],
  steppedVsLevel: [
    {
      category: "steppedVsLevel",
      fieldname: "Transition from Level to Stepped?",
      type: "transitionFromLevelToStepped",
      life: true,
      tpd: true,
      trauma: true,
      ip: false,
      for: "insurance",
      valueType: "boolean",
    },
    {
      category: "steppedVsLevel",
      fieldname: "Number of Years on Level",
      type: "numYearsOnLevel",
      life: 15,
      tpd: 15,
      trauma: 15,
      ip: 15,
      for: "insurance",
      valueType: "number",
    },
    {
      category: "steppedVsLevel",
      fieldname: "% on Stepped",
      type: "percentOnStepped",
      life: 25,
      tpd: 25,
      trauma: 25,
      ip: 25,
      for: "insurance",
      valueType: "percent",
    },
  ],
};

const benchmarking = [{}];

// const globalCols = [
//     { field: "variableName", header}
// ]

export const portfolioCols = [
  { field: "portfolioName", header: "Portfolio", type: "text" },
  {
    field: "investmentTerm",
    header: "Investment Term (Years)",
    type: "number",
  },
  {
    field: "probabilityNegativeReturn",
    header: "Probability of Negative Returns in 1 Year",
    type: "percent",
  },
  {
    field: "expectedGrowth",
    header: "Expected Growth",
    type: "uneditable_percent",
  },
];

// export const assumptionsCols = [
//   {
//     field: "cpi",
//     header: "CPI",
//     type: "text",
//     notEditable: true,
//     rowGroupLabel: "Growth Rate",
//   },
//   {
//     field: "livingExpense",
//     header: "Living Expense",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Growth Rate",
//   },
//   {
//     field: "education",
//     header: "Education",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Growth Rate",
//   },
//   {
//     field: "growthAboveCPI",
//     header: "Growth Above CPI",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Growth Rate",
//   },
//   {
//     field: "depreciatingAsset",
//     header: "Depreciating Asset",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Growth Rate",
//   },

//   {
//     field: "income",
//     header: "Income",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Investment Returns",
//   },
//   {
//     field: "expense",
//     header: "Expense",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Investment Returns",
//   },
//   {
//     field: "marketValue",
//     header: "Market Value",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Reductions",
//   },
//   {
//     field: "deathOrDisabilityOfInsured",
//     header: "Living Expense (death or disability of insured)",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Reductions",
//   },
//   {
//     field: "inRetirement",
//     header: "Living Expense (in retirement)",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Reductions",
//   },
//   {
//     field: "other",
//     header: "Other",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Reductions",
//   },
//   {
//     field: "taxOnIncomeGrowth",
//     header: "Tax on Income Growth",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Taxation",
//   },
//   {
//     field: "taxOnCapitalGrowth",
//     header: "Tax on Capital Growth",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Taxation",
//   },
//   {
//     field: "taxOnFutureCapitalGrowth",
//     header: "Tax on Future Capital Growth",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Taxation",
//   },
//   {
//     field: "taxToBeDeductedFromFutureIncomeReturns",
//     header: "Tax to be deducted from Investment Returns",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Taxation",
//   },
//   {
//     field: "netInvestmentReturn",
//     header: "Net Investment Return",
//     type: "percent",
//     notEditable: true,
//     rowGroupLabel: "Taxation",
//   },
//   {
//     field: "mortalityAge",
//     header: "Mortality Age",
//     type: "number",
//     notEditable: true,
//     rowGroupLabel: "Other",
//   },
//   {
//     field: "yearsOnLevelPremium",
//     header: "Years On Level Premium",
//     type: "number",
//     notEditable: true,
//     rowGroupLabel: "Other",
//   },
//   {
//     field: "yearsUntilRetirementYoungestPartner",
//     header: "Years until Retirement for Youngest Partner",
//     type: "number",
//     notEditable: true,
//     rowGroupLabel: "Other",
//   },
//   {
//     field: "maximumAgeForIncomeProtection",
//     header: "Maximum Age For Income Protection",
//     type: "number",
//     notEditable: true,
//     rowGroupLabel: "Other",
//   },
//   {
//     field: "maximumAgeToFundChildEd",
//     header: "Maximum Age To Fund Child Education",
//     type: "number",
//     notEditable: true,
//     rowGroupLabel: "Other",
//   },
// ];

export const philosophiesCols = [
  {
    requirements: [
      {
        field: "requirements",
        header: "requirement",
        type: "text",
        editable: false,
      },
      { field: "life", header: "Life", type: "percent" },
      { field: "tpd", header: "TPD", type: "percent" },
      { field: "trauma", header: "Trauma", type: "percent" },
      { field: "ip", header: "IP", type: "percent" },
    ],
    offsets: [
      { field: "offset", header: "Offsets", type: "text", editable: false },
      { field: "life", header: "Life", type: "percent" },
      { field: "tpd", header: "TPD", type: "percent" },
      { field: "trauma", header: "Trauma", type: "percent" },
      { field: "ip", header: "IP", type: "percent" },
    ],
    steppedVsLevel: [
      {
        field: "steppedVsLevel",
        header: "Stepped vs. Level",
        type: "text",
        editable: false,
      },
      { field: "life", header: "Life", type: "percent" },
      { field: "tpd", header: "TPD", type: "percent" },
      { field: "trauma", header: "Trauma", type: "percent" },
      { field: "ip", header: "IP", type: "percent" },
    ],
  },
];

export const testData = {
  portfolios,
  assumptions,
  philosophies,
  benchmarking,
};
