// NEED to get the asset class too and add an option to put notes
/* asset/liability and income/expense shape: 
      belongsTo: stateIndexKey,
      idx,
      frequency,
      value,
      type: selectedNodesData[fieldKey].data,
      label: selectedNodesData[fieldKey].label,
      icon: selectedNodesData[fieldKey].icon,
*/

export const tjaart = {
  // testValidation: {
  //   primaryAge: 42,
  //   partnerAge: 42,
  //   numPeople: 4,
  //   numExpenses: 16,
  //   numIncomes: 4,
  //   numPeopleWithExpenses: 4,
  //   numPeopleWithLiabilities: 1,
  //   numPeopleWithAssets: 2,
  //   numPeopleWithIncomes: 2,
  //   totalExpenses: 155362,
  //   totalLiabilities: 90100,
  //   totalAssets: 604119,
  //   totalIncomes: 385827,
  //   people: ["Tjaart", "Cecile", "Nikolas", "Lienke"],
  //   incomesByPerson: {
  //     Tjaart: 2,
  //     Cecile: 2,
  //   },
  //   assetsByPerson: {
  //     Tjaart: 2,
  //     Cecile: 4,
  //   },
  //   liabilitiesByPerson: {
  //     Cecile: 2,
  //   },
  //   expensesByPerson: {
  //     Tjaart: 7,
  //     Cecile: 7,
  //     Nikolas: 1,
  //     Lienke: 1,
  //   },
  //   numLiabilities: 2,
  //   numAssets: 6,
  // },
  hasPartner: true,
  hasDependents: false,
  hasChildren: true,
  hasJointDependents: false,
  hasPartnerDependents: false,
  insuranceInfo: {
    estatePlanning: {},
    existingCover: [],
  },
  primary: {
    // firstName: "Tjaart",
    firstName: "Demo",
    // lastName: "van der Westhuizen",
    lastName: "Client",
    dateOfBirth: "Fri Jun 25 1979",
    relationshipStatus: "married",
    gender: "male",
    wants: [
      "Set up a SMSF",
      "Make better financial decisions",
      "Help the kids out",
      "TEST",
    ],
    expenses: [
      // {
      //   class: "homeExpense",
      //   type: "rentExpense",
      //   value: 12500,
      // },
      {
        class: "insuranceExpense",
        type: "privateHealthInsuranceExpense",
        value: 4269,
        label: "Private Health Insurance",
      },
      {
        class: "insuranceExpense",
        type: "vehicleInsuranceExpense",
        value: 587,
        label: "Vehicle Insurance",
      },
      {
        class: "investmentExpense",
        type: "investmentBondsExpense",
        value: 2105,
        label: "Investment Bonds",
      },
      {
        class: "insuranceExpense",
        type: "lifeInsuranceExpense",
        value: 5008,
        label: "Life Insurance",
      },
      {
        class: "insuranceExpense",
        type: "homeInsuranceExpense",
        value: 4965,
        label: "Home & Contents Insurance",
      },
      {
        class: "homeExpense",
        type: "homeUtilitiesExpense",
        value: 1800,
        label: "Home Utilities",
      },
    ],
    liabilities: [],
    assets: [
      {
        class: "otherInvestments",
        type: "bonds",
        value: 124510,
        notes: "SA Alan Gray Annuity",
        label: "Bonds",
      },
      {
        class: "otherInvestments",
        type: "bonds",
        value: 7017,
        notes: "SA Alan Gray Annuity",
        label: "Bonds",
      },
    ],
    incomes: [
      {
        class: "personalIncome",
        type: "salaryIncome",
        value: 91636,
        label: "Salary Income",
      },
      {
        class: "investmentIncome",
        type: "rentalIncome",
        value: 38181,
        label: "Rental Income",
      },
    ],
    healthStatus: "",
    desiredRetirementAge: 65,
    uiData: {
      name: "man",
      type: "adult",
      src: "/assets/images/6-man.svg",
      width: 62,
      height: 68,
      role: "parent",
      gender: "male",
    },
  },
  joint: {
    expenses: [],
    liabilities: [],
    assets: [],
    incomes: [],
  },
  partner: {
    // firstName: "Cecile",
    // lastName: "van der Westhuizen",
    firstName: "Miss",
    lastName: "Client",
    dateOfBirth: "Fri Jun 25 1979",
    gender: "female",
    wants: [
      "Manage investment portfolio",
      "Invest a lump sum",
      "Check insurance cover and policies",
      "Start a family",
      "Fund education",
      "Manage debt",
      "Contribute to super",
    ],
    expenses: [
      {
        class: "financialExpense",
        type: "personalLoanExpense",
        value: 4108,
        label: "Personal Loan",
      },
      {
        class: "insuranceExpense",
        type: "vehicleInsuranceExpense",
        value: 600,
        label: "Vehicle Insurance",
      },
      {
        class: "investmentExpense",
        type: "investmentBondsExpense",
        value: 1520,
        label: "Investment Bonds",
      },
      {
        class: "homeExpense",
        type: "ratesAndTaxesExpense",
        value: 2052,
        label: "Rates & Taxes",
      },
      {
        class: "homeExpense",
        type: "homeEntertainmentExpense",
        value: 840,
        label: "Home Entertainment",
      },
      {
        class: "livingExpense",
        type: "generalLivingExpenses",
        value: 50000,
        label: "General Living Costs",
      },
      {
        class: "insuranceExpense",
        type: "lifeInsuranceExpense",
        value: 5008,
        label: "Life Insurance",
      },
    ],
    liabilities: [
      {
        class: "mortgage",
        type: "residentialMortgage",
        value: 80100,
        label: "Residential Mortgage",
      },
      {
        class: "otherLoans",
        type: "motorVehicleLoan",
        value: 10000,
        label: "Motor Vehicle Loan",
      },
    ],
    assets: [
      {
        class: "realEstate",
        type: "familyHome",
        value: 3600000,
        label: "Family Home",
      },
      {
        class: "superAndPension",
        type: "pension",
        value: 136142,
        notes: "SA Department of Health Pension Fund",
        label: "Pension",
      },
      {
        class: "otherInvestments",
        type: "bonds",
        value: 90000,
        notes: "SA Alan Gray Annuity",
        label: "Bonds",
      },
      {
        class: "otherInvestments",
        type: "bonds",
        value: 21450,
        notes: "SA Alan Gray Unit Trust",
        label: "Bonds",
      },
      {
        class: "realEstate",
        type: "investmentProperty",
        value: 225000,
        notes: "Share of SA property in Lynnwood",
        label: "Investment Property",
      },
    ],
    incomes: [
      {
        class: "personalIncome",
        type: "salaryIncome",
        value: 247000,
        label: "Salary Income",
      },
      {
        class: "personalIncome",
        type: "otherIncome",
        value: 9010,
        label: "Other Income",
      },
    ],
    healthStatus: "",
    desiredRetirementAge: 70,
    uiData: {
      name: "woman",
      type: "adult",
      src: "/assets/images/7-woman.svg",
      width: 62,
      height: 68,
      role: "parent",
      gender: "female",
    },
  },
  advisors: [],
  dependents: [],
  children: [
    {
      firstName: "Nikolas",
      lastName: "van der Westhuizen",
      legacyNominee: true,
      dateOfBirth: "Wed Jan 1 2015",
      expenses: [
        {
          class: "childExpense",
          type: "childEducationExpense",
          value: 30000,
          label: "Child Education",
        },
        {
          class: "childExpense",
          type: "childcareExpense",
          value: 10000,
          label: "Childcare",
        },
        {
          class: "childExpense",
          type: "childPocketMoneyExpense",
          value: 1000,
          label: "Pocket Money",
        },
      ],
      uiData: {
        name: "boy",
        type: "child",
        src: "/assets/images/2-boy.svg",
        width: 37.199999999999996,
        height: 40.8,
        role: "child",
        gender: "male",
      },
    },
    {
      firstName: "Lienke",
      lastName: "van der Westhuizen",
      legacyNominee: true,
      dateOfBirth: "Wed Jan 1 2015",
      expenses: [
        {
          class: "childExpense",
          type: "childEducationExpense",
          value: 30000,
          label: "Child Education",
        },
      ],
      uiData: {
        name: "girl",
        type: "child",
        src: "/assets/images/3-girl.svg",
        width: 37.199999999999996,
        height: 40.8,
        role: "child",
        gender: "female",
      },
    },
  ],
  partnerDependents: [],
  jointDependents: [],

  values: {
    selectedVals: [
      "Security",
      "Health",
      "Growth",
      "Rationality",
      "Tradition",
      "Independence",
    ],
    topVals: ["Health", "Tradition", "Growth", "Independence", "Rationality"],
    topValsWhy: {
      Health: "Health is important",
      Tradition: "Tradition is traditional",
      Growth: "Bigger is better",
      Independence: "I like being my own boss",
      Rationality: "Better than the opposite",
    },
  },
  goals: [
    {
      id: "Btb4G",
      goal: "Education",
      idx: 8,
      left: 1194,
      top: 174,
      arrIdx: 0,
    },
    {
      id: "PdaHI",
      goal: "Arrange Financial Documents",
      idx: 46,
      left: 547,
      top: 71,
      arrIdx: 1,
    },
    {
      id: "WHNql",
      goal: "Restructure Superannuation",
      idx: 47,
      left: 147,
      top: 332,
      arrIdx: 2,
    },
    {
      id: "EXSVp",
      goal: "Buy/Build a Residential Property",
      idx: 14,
      left: 922,
      top: 279,
      arrIdx: 3,
    },
  ],
};
