export const funds = [
  {
    id: "0",
    fund: "Cash",
    apir: "",
    Cash: 100,
    Conservative: 6,
    "Mod Conservative": 3,
    "Mod Growth": 2,
    Growth: 2,
    "High Growth": 2,
  },
  {
    id: "1",
    fund: "DFA 2 Year Diversified",
    apir: "DFA0002AU",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 0,
    "Mod Growth": 0,
    Growth: 0,
    "High Growth": 0,
  },
  {
    id: "2",
    fund: "VG Australian FI",
    apir: "VAN0001AU",
    Cash: 0,
    Conservative: 8,
    "Mod Conservative": 5,
    "Mod Growth": 4,
    Growth: 0,
    "High Growth": 0,
  },
  {
    id: "3",
    fund: "DFA Global Bond Trust",
    apir: "DFA0028AU",
    Cash: 0,
    Conservative: 9,
    "Mod Conservative": 8,
    "Mod Growth": 5,
    Growth: 0,
    "High Growth": 0,
  },
  {
    id: "4",
    fund: "Winton",
    apir: "MAQ0482AU",
    Cash: 0,
    Conservative: 5,
    "Mod Conservative": 6,
    "Mod Growth": 7,
    Growth: 8,
    "High Growth": 9,
  },
  {
    id: "5",
    fund: "VG Balanced",
    apir: "VAN0108AU",
    Cash: 0,
    Conservative: 32,
    "Mod Conservative": 25,
    "Mod Growth": 22,
    Growth: 23,
    "High Growth": 16,
  },
  {
    id: "6",
    fund: "VG Conservative",
    apir: "VAN0109AU",
    Cash: 0,
    Conservative: 15,
    "Mod Conservative": 4,
    "Mod Growth": 3,
    Growth: 2,
    "High Growth": 1,
  },
  {
    id: "7",
    fund: "VG Growth",
    apir: "VAN0110AU",
    Cash: 0,
    Conservative: 4,
    "Mod Conservative": 5,
    "Mod Growth": 6,
    Growth: 9,
    "High Growth": 9,
  },
  {
    id: "8",
    fund: "VG High Growth",
    apir: "VAN0111AU",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 3,
    "Mod Growth": 4,
    Growth: 5,
    "High Growth": 9,
  },
  {
    id: "9",
    fund: "DFA Emerging Markets",
    apir: "DFA0107AU",
    Cash: 0,
    Conservative: 3,
    "Mod Conservative": 4,
    "Mod Growth": 5,
    Growth: 8,
    "High Growth": 8,
  },
  {
    id: "10",
    fund: "AG Australian Equity",
    apir: "ETL0060AU",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 3,
    "Mod Growth": 6,
    Growth: 9,
    "High Growth": 12,
  },
  {
    id: "11",
    fund: "Talaria",
    apir: "AUS0035AU",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 5,
    "Mod Growth": 7,
    Growth: 8,
    "High Growth": 8,
  },
  {
    id: "12",
    fund: "MVW",
    apir: "AU000000MVW8",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 5,
    "Mod Growth": 5,
    Growth: 7,
    "High Growth": 8,
  },
  {
    id: "13",
    fund: "Van Eck Vectors MSCI",
    apir: "AU00000QUAL9",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 5,
    "Mod Growth": 5,
    Growth: 6,
    "High Growth": 9,
  },
  {
    id: "14",
    fund: "Ardea",
    apir: "HOW0098AU",
    Cash: 0,
    Conservative: 18,
    "Mod Conservative": 17,
    "Mod Growth": 13,
    Growth: 6,
    "High Growth": 0,
  },
  {
    id: "15",
    fund: "Global Core Equity Trust",
    apir: "DFA0004AU",
    Cash: 0,
    Conservative: 0,
    "Mod Conservative": 2,
    "Mod Growth": 6,
    Growth: 7,
    "High Growth": 9,
  },
];
