export const philosophies = {
  requirements: [
    // Liabilities:
    {
      category: "requirements",
      type: "residentialMortgage",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "investmentMortgage",
      life: 1,
      tpd: 1,
      trauma: 0.15,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "otherDebt",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "motorVehicleLoan",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "creditCardBalance",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "personalLoan",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    {
      category: "requirements",
      type: "marginLoanOnShares",
      life: 1,
      tpd: 1,
      trauma: 0.3,
      ip: undefined,
      for: "liabilities",
    },
    // Expenses:
    {
      category: "requirements",
      type: "childEducationExpense",
      life: 1,
      tpd: 1,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
    },
    {
      category: "requirements",
      type: "rentExpense",
      life: 1,
      tpd: 1,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
    },
    {
      category: "requirements",
      type: "livingExpense",
      life: 0.75,
      tpd: 0.75,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
    },
    {
      category: "requirements",
      type: "generalLivingExpenses",
      life: 0.75,
      tpd: 0.75,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
    },

    // additional requirements:
    {
      category: "requirements",
      type: "replacementIncome",
      life: undefined,
      tpd: undefined,
      trauma: 1,
      ip: 0.75,
      for: "incomes",
    },
    {
      category: "requirements",
      type: "replacementIncomeNumMonths",
      life: undefined,
      tpd: undefined,
      trauma: 6,
      ip: undefined,
      for: "incomes",
    },
    {
      category: "requirements",
      type: "medicalRequirements",
      life: undefined,
      tpd: 200000,
      trauma: 200000,
      ip: undefined,
      for: "additionalRequirements",
    },
    {
      category: "requirements",
      type: "extraHelpRequired",
      life: undefined,
      tpd: 30000,
      trauma: undefined,
      ip: undefined,
      for: "expenses",
    },
    {
      category: "requirements",
      type: "changeOfHousingCar",
      life: undefined,
      tpd: 180000,
      trauma: undefined,
      ip: undefined,
      for: "additionalRequirements",
    },
    {
      category: "requirements",
      type: "lumpSumLegacy",
      life: true,
      tpd: false,
      trauma: false,
      ip: false,
      for: "additionalRequirements",
    },
    {
      category: "requirements",
      type: "partnerTimeOffWorkInMonths",
      life: 3,
      tpd: 3,
      trauma: 3,
      ip: undefined,
      for: "incomes",
    },
    {
      category: "requirements",
      type: "minimumCoveragePercentOfRequirementsPreOffsets",
      life: 0.25,
      tpd: 0.25,
      trauma: 0.25,
      ip: undefined,
      for: "additionalRequirements",
    },
  ],

  offsets: [
    // ASSETS:
    {
      category: "offsets",
      type: "investmentProperty",
      life: 0.85,
      tpd: 0.85,
      trauma: 0,
      ip: undefined,
      for: "assets",
    },
    // Any investment/asset that is not cash or investmentProperty or art:
    {
      category: "offsets",
      type: "nonCashInvestments",
      life: 0.85,
      tpd: 0.85,
      trauma: 0.5,
      ip: undefined,
      for: "assets",
    },
    {
      category: "offsets",
      type: "superAndPension",
      life: 0.85,
      tpd: 0.85,
      trauma: 0,
      ip: undefined,
      for: "assets",
    },
    {
      category: "offsets",
      type: "cash",
      life: 1,
      tpd: 1,
      trauma: 0.85,
      ip: undefined,
      for: "assets",
    },
    // WHAT ARE THESE?
    {
      category: "offsets",
      type: "offsetAccounts",
      life: 100,
      tpd: 100,
      trauma: 30,
      ip: undefined,
      for: "assets",
    },
    {
      category: "offsets",
      type: "artOrAntique",
      life: 0.85,
      tpd: 0.85,
      trauma: 0,
      ip: undefined,
      for: "assets",
    },
    {
      category: "offsets",
      type: "incomeProtector", // ??
      life: undefined,
      tpd: 1,
      trauma: 0,
      ip: undefined,
      for: "assets",
    },
    // INCOME
    {
      category: "offsets",
      type: "livingPartnerIncome",
      life: 0.5,
      tpd: 1,
      trauma: 0,
      ip: 0,
      for: "incomes",
    },
    {
      category: "offsets",
      type: "otherIncome",
      life: 1,
      tpd: 1,
      trauma: 1,
      ip: 0,
      for: "incomes",
    },
    {
      category: "offsets",
      type: "otherLumpSums",
      life: 1,
      tpd: 1,
      trauma: 0,
      ip: 0,
      for: "additionalRequirements",
    },
  ],
  steppedVsLevel: [
    {
      category: "steppedVsLevel",
      type: "transitionFromLevelToStepped",
      life: true,
      tpd: true,
      trauma: true,
      ip: false,
      for: "insurance",
    },
    {
      category: "steppedVsLevel",
      type: "numYearsOnLevel",
      life: 15,
      tpd: 15,
      trauma: 15,
      ip: 15,
      for: "insurance",
    },
    {
      category: "steppedVsLevel",
      type: "percentOnStepped",
      life: 0.25,
      tpd: 0.25,
      trauma: 0.25,
      ip: 0.25,
      for: "insurance",
    },
  ],
};
