/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreatePreassessment = /* GraphQL */ `
  subscription OnCreatePreassessment {
    onCreatePreassessment {
      id
      advisorId
      clientId
      advisorName
      dealerGroup
      clientName
      dob
      gender
      healthInfo
      preassessmentData
      attachments
      underwriters {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      underwriterIDs
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePreassessment = /* GraphQL */ `
  subscription OnUpdatePreassessment {
    onUpdatePreassessment {
      id
      advisorId
      clientId
      advisorName
      dealerGroup
      clientName
      dob
      gender
      healthInfo
      preassessmentData
      attachments
      underwriters {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      underwriterIDs
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePreassessment = /* GraphQL */ `
  subscription OnDeletePreassessment {
    onDeletePreassessment {
      id
      advisorId
      clientId
      advisorName
      dealerGroup
      clientName
      dob
      gender
      healthInfo
      preassessmentData
      attachments
      underwriters {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      underwriterIDs
      createdAt
      updatedAt
    }
  }
`;
export const onCreatePreassessmentResponse = /* GraphQL */ `
  subscription OnCreatePreassessmentResponse {
    onCreatePreassessmentResponse {
      id
      underwriterID
      clientID
      clientFullName
      underwriterFullName
      underwriterCompany
      advisorID
      preassessmentID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      response
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePreassessmentResponse = /* GraphQL */ `
  subscription OnUpdatePreassessmentResponse {
    onUpdatePreassessmentResponse {
      id
      underwriterID
      clientID
      clientFullName
      underwriterFullName
      underwriterCompany
      advisorID
      preassessmentID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      response
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePreassessmentResponse = /* GraphQL */ `
  subscription OnDeletePreassessmentResponse {
    onDeletePreassessmentResponse {
      id
      underwriterID
      clientID
      clientFullName
      underwriterFullName
      underwriterCompany
      advisorID
      preassessmentID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      response
      createdAt
      updatedAt
    }
  }
`;
export const onCreatePreassessmentResponseUnderwriterAdvisor = /* GraphQL */ `
  subscription OnCreatePreassessmentResponseUnderwriterAdvisor {
    onCreatePreassessmentResponseUnderwriterAdvisor {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePreassessmentResponseUnderwriterAdvisor = /* GraphQL */ `
  subscription OnUpdatePreassessmentResponseUnderwriterAdvisor {
    onUpdatePreassessmentResponseUnderwriterAdvisor {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePreassessmentResponseUnderwriterAdvisor = /* GraphQL */ `
  subscription OnDeletePreassessmentResponseUnderwriterAdvisor {
    onDeletePreassessmentResponseUnderwriterAdvisor {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreatePreassessmentUnderwriter = /* GraphQL */ `
  subscription OnCreatePreassessmentUnderwriter {
    onCreatePreassessmentUnderwriter {
      id
      clientID
      advisorID
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePreassessmentUnderwriter = /* GraphQL */ `
  subscription OnUpdatePreassessmentUnderwriter {
    onUpdatePreassessmentUnderwriter {
      id
      clientID
      advisorID
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePreassessmentUnderwriter = /* GraphQL */ `
  subscription OnDeletePreassessmentUnderwriter {
    onDeletePreassessmentUnderwriter {
      id
      clientID
      advisorID
      underwriterID
      underwriter {
        id
        email
        password
        firstName
        lastName
        employerName
        businessNumber
        mobile
        phone
        status
        preassessments {
          nextToken
        }
        preassessmentResponses {
          nextToken
        }
        createdAt
        updatedAt
      }
      preassessmentID
      preassessment {
        id
        advisorId
        clientId
        advisorName
        dealerGroup
        clientName
        dob
        gender
        healthInfo
        preassessmentData
        attachments
        underwriters {
          nextToken
        }
        underwriterIDs
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreateUnderwriter = /* GraphQL */ `
  subscription OnCreateUnderwriter {
    onCreateUnderwriter {
      id
      email
      password
      firstName
      lastName
      employerName
      businessNumber
      mobile
      phone
      status
      preassessments {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      preassessmentResponses {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateUnderwriter = /* GraphQL */ `
  subscription OnUpdateUnderwriter {
    onUpdateUnderwriter {
      id
      email
      password
      firstName
      lastName
      employerName
      businessNumber
      mobile
      phone
      status
      preassessments {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      preassessmentResponses {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteUnderwriter = /* GraphQL */ `
  subscription OnDeleteUnderwriter {
    onDeleteUnderwriter {
      id
      email
      password
      firstName
      lastName
      employerName
      businessNumber
      mobile
      phone
      status
      preassessments {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      preassessmentResponses {
        items {
          id
          clientID
          advisorID
          underwriterID
          preassessmentID
          createdAt
          updatedAt
        }
        nextToken
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreateAdvisor = /* GraphQL */ `
  subscription OnCreateAdvisor($id: String!) {
    onCreateAdvisor(id: $id) {
      id
      clients {
        items {
          id
          clientID
          advisorID
          createdAt
          updatedAt
        }
        nextToken
      }
      advisorProfile {
        email
        mobile
        phone
        firstName
        lastName
        logo
        profilePicture
        addressOne
        addressTwo
        city
        state
        country
        currency
        employerName
        businessNumber
        dealerGroup
        dealerGroupNumber
      }
      assumptions
      philosophies
      portfolios
      licenseeAllocations
      fixedBands
      benchmarkingProfile
      benchmarkingWeightings
      underwriters
      funds
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateAdvisor = /* GraphQL */ `
  subscription OnUpdateAdvisor($id: String!) {
    onUpdateAdvisor(id: $id) {
      id
      clients {
        items {
          id
          clientID
          advisorID
          createdAt
          updatedAt
        }
        nextToken
      }
      advisorProfile {
        email
        mobile
        phone
        firstName
        lastName
        logo
        profilePicture
        addressOne
        addressTwo
        city
        state
        country
        currency
        employerName
        businessNumber
        dealerGroup
        dealerGroupNumber
      }
      assumptions
      philosophies
      portfolios
      licenseeAllocations
      fixedBands
      benchmarkingProfile
      benchmarkingWeightings
      underwriters
      funds
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteAdvisor = /* GraphQL */ `
  subscription OnDeleteAdvisor($id: String!) {
    onDeleteAdvisor(id: $id) {
      id
      clients {
        items {
          id
          clientID
          advisorID
          createdAt
          updatedAt
        }
        nextToken
      }
      advisorProfile {
        email
        mobile
        phone
        firstName
        lastName
        logo
        profilePicture
        addressOne
        addressTwo
        city
        state
        country
        currency
        employerName
        businessNumber
        dealerGroup
        dealerGroupNumber
      }
      assumptions
      philosophies
      portfolios
      licenseeAllocations
      fixedBands
      benchmarkingProfile
      benchmarkingWeightings
      underwriters
      funds
      createdAt
      updatedAt
    }
  }
`;
export const onCreateAdvisorClient = /* GraphQL */ `
  subscription OnCreateAdvisorClient($advisorID: String!) {
    onCreateAdvisorClient(advisorID: $advisorID) {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateAdvisorClient = /* GraphQL */ `
  subscription OnUpdateAdvisorClient($advisorID: String!) {
    onUpdateAdvisorClient(advisorID: $advisorID) {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteAdvisorClient = /* GraphQL */ `
  subscription OnDeleteAdvisorClient($advisorID: String!) {
    onDeleteAdvisorClient(advisorID: $advisorID) {
      id
      clientID
      client {
        id
        advisorID
        advisor {
          id
          assumptions
          philosophies
          portfolios
          licenseeAllocations
          fixedBands
          benchmarkingProfile
          benchmarkingWeightings
          underwriters
          funds
          createdAt
          updatedAt
        }
        hasPartner
        hasDependents
        hasChildren
        hasJointDependents
        hasPartnerDependents
        goals
        values
        insuranceInfo
        riskProfile
        riskProfileScores
        primary {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        partner {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          relationshipStatus
          employmentDetails
          contactDetails
          employed
          jobTitle
          jobIndustry
          employmentStatus
          employerName
          employmentStartDate
          desiredRetirementAge
          email
          mobile
          streetAddress
          streetAddress2
          city
          state
          zipCode
          existingStructures
          existingStructuresAndAdvisors
          wants
          whyMoney
          healthInfo
          authorities
          estatePlanning
          uiData
          preassessmentIDs
        }
        advisors
        children {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        dependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        partnerDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        jointDependents {
          firstName
          lastName
          dateOfBirth
          gender
          healthStatus
          uiData
          legacyNominee
          relatedTo
          studying
          studyingStatus
          studyingCompletionDate
          legacyAmount
        }
        authoritiesData
        healthInfo
        existingStructureDetails
        existingStructures
        createdAt
        updatedAt
      }
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreateClient = /* GraphQL */ `
  subscription OnCreateClient($advisorID: String!) {
    onCreateClient(advisorID: $advisorID) {
      id
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      hasPartner
      hasDependents
      hasChildren
      hasJointDependents
      hasPartnerDependents
      goals
      values
      insuranceInfo
      riskProfile
      riskProfileScores
      primary {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      partner {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      joint {
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
      }
      advisors
      children {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      dependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      partnerDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      jointDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      authoritiesData
      healthInfo
      existingStructureDetails
      existingStructures
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateClient = /* GraphQL */ `
  subscription OnUpdateClient($advisorID: String!) {
    onUpdateClient(advisorID: $advisorID) {
      id
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      hasPartner
      hasDependents
      hasChildren
      hasJointDependents
      hasPartnerDependents
      goals
      values
      insuranceInfo
      riskProfile
      riskProfileScores
      primary {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      partner {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      joint {
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
      }
      advisors
      children {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      dependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      partnerDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      jointDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      authoritiesData
      healthInfo
      existingStructureDetails
      existingStructures
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteClient = /* GraphQL */ `
  subscription OnDeleteClient($advisorID: String!) {
    onDeleteClient(advisorID: $advisorID) {
      id
      advisorID
      advisor {
        id
        clients {
          nextToken
        }
        advisorProfile {
          email
          mobile
          phone
          firstName
          lastName
          logo
          profilePicture
          addressOne
          addressTwo
          city
          state
          country
          currency
          employerName
          businessNumber
          dealerGroup
          dealerGroupNumber
        }
        assumptions
        philosophies
        portfolios
        licenseeAllocations
        fixedBands
        benchmarkingProfile
        benchmarkingWeightings
        underwriters
        funds
        createdAt
        updatedAt
      }
      hasPartner
      hasDependents
      hasChildren
      hasJointDependents
      hasPartnerDependents
      goals
      values
      insuranceInfo
      riskProfile
      riskProfileScores
      primary {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      partner {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        relationshipStatus
        employmentDetails
        contactDetails
        employed
        jobTitle
        jobIndustry
        employmentStatus
        employerName
        employmentStartDate
        desiredRetirementAge
        email
        mobile
        streetAddress
        streetAddress2
        city
        state
        zipCode
        existingStructures
        existingStructuresAndAdvisors
        wants
        whyMoney
        healthInfo
        authorities
        estatePlanning
        uiData
        preassessmentIDs
      }
      joint {
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
      }
      advisors
      children {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      dependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      partnerDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      jointDependents {
        firstName
        lastName
        dateOfBirth
        gender
        expenses {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        liabilities {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        assets {
          id
          type
          parentType
          label
          value
          division
          notes
          icon
          bucket
        }
        incomes {
          id
          type
          parentType
          label
          value
          frequency
          division
          notes
          icon
          bucket
        }
        healthStatus
        uiData
        legacyNominee
        relatedTo
        studying
        studyingStatus
        studyingCompletionDate
        legacyAmount
      }
      authoritiesData
      healthInfo
      existingStructureDetails
      existingStructures
      createdAt
      updatedAt
    }
  }
`;
